---
sudo: required
services:
- docker
language: ruby
cache: bundler
rvm:
  - 2.4.1
before_install:
- docker run -d --name=clickhouse-server -p 127.0.0.1:8123:8123 yandex/clickhouse-server
- docker run --rm --link clickhouse-server:clickhouse-server yandex/clickhouse-client --host clickhouse-server --query="CREATE DATABASE stat"
- gem install bundler -v 1.16.3
script:
- bundle exec rake spec
- bundle exec rubocop --fail-level C
